In [84]:
import pandas as pd 
import numpy as np 
from pymongo import MongoClient 
from sqlalchemy import create_engine 
from scipy.stats import ttest_ind 
from sklearn.cluster import KMeans 
from sklearn.preprocessing import StandardScaler

In [85]:
client = MongoClient("mongodb://localhost:27017/") 
db = client["nimbus_events"] 
activity = pd.DataFrame( list(db.user_activity_logs.find()) ) 
activity.head()

,_id,customer_id,member_id,timestamp,event_type,page_url,session_duration_sec,browser,os,device_type,timezone,ip_address,userId,customerId,referrer,feature,userID
0,6a1aaafd0b201fc2f0a25964,229,410.0,2024-01-16 10:13:48,form_submit,/projects/1779,2263.0,Chrome,iOS 17,mobile,UTC,60.214.112.115,NaN,NaN,NaN,NaN,NaN
1,6a1aaafd0b201fc2f0a25965,14,2616.0,2024-06-12 13:27:31,search,/projects/3627,NaN,Safari,Windows 10,desktop,Asia/Kolkata,NaN,NaN,NaN,NaN,NaN,NaN
2,6a1aaafd0b201fc2f0a25966,NaN,NaN,2025-09-03 13:23:25,notification_click,/api-docs,2915.0,NaN,NaN,NaN,America/Los_Angeles,NaN,1292.0,776,NaN,NaN,NaN
3,6a1aaafd0b201fc2f0a25967,334,6066.0,2024-02-19 17:39:16,dashboard_view,/api-docs,730.0,NaN,NaN,NaN,America/Chicago,NaN,NaN,NaN,NaN,NaN,NaN
4,6a1aaafd0b201fc2f0a25968,115,3753.0,2024-05-05 00:56:31,import,/team,2353.0,Safari Mobile,macOS 14,desktop,NaN,200.134.219.230,NaN,NaN,NaN,NaN,NaN

In [86]:
activity.columns = ( activity.columns .str.strip() .str.lower() )

In [87]:
activity.head()

,_id,customer_id,member_id,timestamp,event_type,page_url,session_duration_sec,browser,os,device_type,timezone,ip_address,userid,customerid,referrer,feature,userid
0,6a1aaafd0b201fc2f0a25964,229,410.0,2024-01-16 10:13:48,form_submit,/projects/1779,2263.0,Chrome,iOS 17,mobile,UTC,60.214.112.115,NaN,NaN,NaN,NaN,NaN
1,6a1aaafd0b201fc2f0a25965,14,2616.0,2024-06-12 13:27:31,search,/projects/3627,NaN,Safari,Windows 10,desktop,Asia/Kolkata,NaN,NaN,NaN,NaN,NaN,NaN
2,6a1aaafd0b201fc2f0a25966,NaN,NaN,2025-09-03 13:23:25,notification_click,/api-docs,2915.0,NaN,NaN,NaN,America/Los_Angeles,NaN,1292.0,776,NaN,NaN,NaN
3,6a1aaafd0b201fc2f0a25967,334,6066.0,2024-02-19 17:39:16,dashboard_view,/api-docs,730.0,NaN,NaN,NaN,America/Chicago,NaN,NaN,NaN,NaN,NaN,NaN
4,6a1aaafd0b201fc2f0a25968,115,3753.0,2024-05-05 00:56:31,import,/team,2353.0,Safari Mobile,macOS 14,desktop,NaN,200.134.219.230,NaN,NaN,NaN,NaN,NaN

In [88]:
activity.shape

(51485, 17)

In [89]:
activity.isnull().sum()

_id                         0
customer_id             12909
member_id               20659
timestamp                   0
event_type                  0
page_url                    0
session_duration_sec    10333
browser                  7760
os                       7760
device_type              7760
timezone                 4673
ip_address              36030
userid                  38576
customerid              38576
referrer                41020
feature                 44110
userid                  43735
dtype: int64

In [90]:
if "customerid" in activity.columns: 
    activity["customer_id"] = ( activity["customer_id"] .fillna(activity["customerid"]) )

In [91]:
activity = activity.drop(columns=["customerid"],errors="ignore")

In [92]:
# Remove duplicate column names
activity = activity.loc[:,~activity.columns.duplicated()]

In [93]:
if "userid" in activity.columns:

    activity["member_id"] = (
        activity["member_id"]
        .fillna(activity["userid"])
    )

activity = activity.drop(
    columns=["userid"],
    errors="ignore"
)

In [94]:
activity= activity.drop(columns="_id").head()

In [95]:
activity = activity.dropna( subset=["customer_id"] )

In [96]:
activity["session_duration_sec"] = ( activity["session_duration_sec"] .fillna(0) )

In [97]:
activity["event_type"] = ( activity["event_type"] .fillna("unknown") )

In [98]:
Q1 = activity["session_duration_sec"].quantile(0.25) 
Q3 = activity["session_duration_sec"].quantile(0.75) 
IQR = Q3 - Q1 
lower_bound = Q1 - 1.5 * IQR 
upper_bound = Q3 + 1.5 * IQR 
activity = activity[ ( activity["session_duration_sec"] >= lower_bound ) & ( activity["session_duration_sec"] <= upper_bound ) ]

In [99]:
print("\nCleaned Dataset Preview:") 
activity.head()

Cleaned Dataset Preview:

,customer_id,member_id,timestamp,event_type,page_url,session_duration_sec,browser,os,device_type,timezone,ip_address,referrer,feature
0,229,410.0,2024-01-16 10:13:48,form_submit,/projects/1779,2263.0,Chrome,iOS 17,mobile,UTC,60.214.112.115,NaN,NaN
1,14,2616.0,2024-06-12 13:27:31,search,/projects/3627,0.0,Safari,Windows 10,desktop,Asia/Kolkata,NaN,NaN,NaN
2,776,1292.0,2025-09-03 13:23:25,notification_click,/api-docs,2915.0,NaN,NaN,NaN,America/Los_Angeles,NaN,NaN,NaN
3,334,6066.0,2024-02-19 17:39:16,dashboard_view,/api-docs,730.0,NaN,NaN,NaN,America/Chicago,NaN,NaN,NaN
4,115,3753.0,2024-05-05 00:56:31,import,/team,2353.0,Safari Mobile,macOS 14,desktop,NaN,200.134.219.230,NaN,NaN

survey responses data

In [100]:
db = client["nimbus_events"] 
survey_responses = pd.DataFrame( list(db.nps_survey_responses.find()) ) 
survey_responses.head()

,_id,customer_id,member_id,survey_date,nps_score,category,feedback,survey_channel,response_time_hours
0,6a1aab010b201fc2f0a32281,524,7887,2023-09-04 02:24:00,9,promoter,"Mobile app works great, can manage tasks on th...",email,47.1
1,6a1aab010b201fc2f0a32282,1028,8318,2025-08-08 18:24:23,6,detractor,Admin settings are a nightmare to configure.,in_app,17.5
2,6a1aab010b201fc2f0a32283,901,7774,2024-09-22 22:50:41,2,detractor,Switched from competitor and regret it honestly.,in_app,NaN
3,6a1aab010b201fc2f0a32284,1029,6545,2024-03-28 23:24:08,9,promoter,Support team is incredibly responsive and help...,email,49.9
4,6a1aab010b201fc2f0a32285,411,5896,2025-01-25 23:06:21,4,detractor,Way too expensive for what it offers.,in_app,NaN

In [101]:
survey_responses = survey_responses.loc[ :, ~survey_responses.columns.duplicated() ]

In [102]:
if "customerid" in survey_responses.columns: 
    survey_responses["customer_id"] = ( survey_responses["customer_id"] .fillna( survey_responses["customerId"] ) )

In [103]:
if "memberid" in survey_responses.columns: 
    survey_responses["member_id"] = ( survey_responses["member_id"] .fillna( survey_responses["memberId"] ) )

In [104]:
survey_responses = survey_responses.drop( columns=[ "_id","customerId","memberId"], errors="ignore" )

In [105]:
survey_responses.head(2)

,customer_id,member_id,survey_date,nps_score,category,feedback,survey_channel,response_time_hours
0,524,7887,2023-09-04 02:24:00,9,promoter,"Mobile app works great, can manage tasks on th...",email,47.1
1,1028,8318,2025-08-08 18:24:23,6,detractor,Admin settings are a nightmare to configure.,in_app,17.5

In [106]:
db = client["nimbus_events"] 
onboarding_events = pd.DataFrame( list(db.onboarding_events.find()) ) 
onboarding_events.head(2)

,_id,customer_id,member_id,step,step_index,timestamp,completed,duration_seconds,source,customerId,memberId,workspace_name,integration_name,invitees_count
0,6a1aab010b201fc2f0a32e39,460.0,3234.0,signup,0,2024-01-17 06:33:50,True,1297,NaN,NaN,NaN,NaN,NaN,NaN
1,6a1aab010b201fc2f0a32e3a,901.0,1008.0,first_login,2,2023-04-29 22:50:54,True,1345,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
onboarding_events = onboarding_events.loc[ :, ~onboarding_events.columns.duplicated() ]

In [108]:
if "customerid" in onboarding_events.columns: 
    onboarding_events["customer_id"] = ( onboarding_events["customer_id"] .fillna( onboarding_events["customerId"] ) )

In [109]:
if "memberid" in onboarding_events.columns: 
    onboarding_events["member_id"] = ( onboarding_events["member_id"] .fillna( onboarding_events["memberId"] ) )

In [110]:
onboarding_events = onboarding_events.drop( columns=[ "_id","customerId","memberId"], errors="ignore" )

In [111]:
onboarding_events.head(2)

,customer_id,member_id,step,step_index,timestamp,completed,duration_seconds,source,workspace_name,integration_name,invitees_count
0,460.0,3234.0,signup,0,2024-01-17 06:33:50,True,1297,NaN,NaN,NaN,NaN
1,901.0,1008.0,first_login,2,2023-04-29 22:50:54,True,1345,NaN,NaN,NaN,NaN

In [112]:
activity.to_csv("activity_clean.csv", index=False)

survey_responses.to_csv("survey_clean.csv",index=False)

onboarding_events.to_csv("onboarding_clean.csv",index=False)

sql dataset

In [113]:
# MySQL connection

engine = create_engine('mysql+pymysql://root:MySQL%401234@localhost:3306/assignment')

In [114]:
customers_df = pd.read_sql("SELECT * FROM customers", engine)

subscriptions_df = pd.read_sql(" SELECT * FROM subscriptions ", engine)

tickets_df = pd.read_sql("SELECT * FROM support_tickets", engine)

plan_df = pd.read_sql("select * from plans", engine)

feature_df = pd.read_sql("SELECT * from feature_flags", engine)

team_df = pd.read_sql("SELECT * from team_members",engine)

billing_df= pd.read_sql("select * from billing_invoices",engine)

Customer data

In [115]:
customers_df.head()

,customer_id,company_name,industry,company_size,country_code,country_name,timezone,contact_email,contact_name,signup_date,signup_source,is_active,churned_at,churn_reason,nps_score,created_at,updated_at
0,1,Rush Platform,E-commerce,small,FR,France,Europe/Paris,michael.baker@corp.net,Michael Baker,2023-01-31,partner,0,2024-02-26 10:13:36,Outgrew the platform,NaN,2026-05-29 15:18:46,2026-05-29 15:18:46
1,2,TrekStack,Manufacturing,small,CA,Canada,America/Toronto,emily.moore+work@startup.co,Emily Moore,2023-06-09,referral,1,NaT,None,NaN,2026-05-29 15:18:46,2026-05-29 15:18:46
2,3,Wave Group,Education,enterprise,US,United States,America/New_York,olga.robinson@wavegroup.com,Olga Robinson,2023-10-28,organic,1,NaT,None,NaN,2026-05-29 15:18:46,2026-05-29 15:18:46
3,4,KeenSoftware,Technology,large,GB,United Kingdom,Europe/London,lars.jackson@outlook.com,Lars Jackson,2024-04-09,partner,1,NaT,None,7.0,2026-05-29 15:18:46,2026-05-29 15:18:46
4,5,QuestAnalytics,Logistics,large,US,United States,America/Chicago,joshua.green@yahoo.com,Joshua Green,2023-10-04,partner,1,NaT,None,NaN,2026-05-29 15:18:46,2026-05-29 15:18:46

In [116]:
customers_df.shape

(1204, 17)

In [117]:
customers_df.isnull().sum()

customer_id        0
company_name       0
industry           2
company_size       2
country_code       2
country_name       2
timezone           2
contact_email      2
contact_name       2
signup_date        0
signup_source      1
is_active          0
churned_at       938
churn_reason     991
nps_score        488
created_at         0
updated_at         0
dtype: int64

In [118]:
customers_df.duplicated().sum()

np.int64(0)

In [119]:
cols = [
    "industry",
    "company_size",
    "country_code",
    "country_name",
    "timezone",
    "contact_email",
    "contact_name"
]

customers_df[cols] = customers_df[cols].fillna("Unknown")

In [120]:
customers_df["nps_score"] = ( customers_df["nps_score"] .fillna( customers_df["nps_score"].median() ) )

In [121]:
customers_df["churn_reason"] = ( customers_df["churn_reason"] .fillna("Not Churned") )

In [122]:
date_cols = [ "signup_date", "created_at", "updated_at", "churned_at" ] 
for col in date_cols: 
    customers_df[col] = pd.to_datetime( customers_df[col], errors="coerce" )

In [123]:
customers_df.isnull().sum()

customer_id        0
company_name       0
industry           0
company_size       0
country_code       0
country_name       0
timezone           0
contact_email      0
contact_name       0
signup_date        0
signup_source      1
is_active          0
churned_at       938
churn_reason       0
nps_score          0
created_at         0
updated_at         0
dtype: int64

In [124]:
customers_df.to_csv("clean_customer_data.csv",index=False)

plan data

In [125]:
plan_df.head()

,plan_id,plan_name,plan_tier,monthly_price_usd,annual_price_usd,max_users,max_projects,storage_gb,is_active,created_at
0,1,Free,free,0.0,0.0,5.0,3.0,1,1,2026-05-29 15:18:30
1,2,Starter,starter,12.0,120.0,15.0,10.0,5,1,2026-05-29 15:18:30
2,3,Starter Plus,starter,19.0,190.0,25.0,20.0,10,1,2026-05-29 15:18:30
3,4,Professional,professional,39.0,390.0,50.0,50.0,25,1,2026-05-29 15:18:30
4,5,Professional Plus,professional,59.0,590.0,100.0,100.0,50,1,2026-05-29 15:18:30

In [126]:
plan_df.shape

(8, 10)

In [127]:
plan_df.isnull().sum()

plan_id              0
plan_name            0
plan_tier            0
monthly_price_usd    0
annual_price_usd     0
max_users            1
max_projects         2
storage_gb           0
is_active            0
created_at           0
dtype: int64

In [128]:
plan_df.duplicated().sum()

np.int64(0)

In [129]:
plan_df[["max_users", "max_projects"]] = plan_df[["max_users","max_projects"]].fillna(0)

In [130]:
plan_df.isnull().sum()

plan_id              0
plan_name            0
plan_tier            0
monthly_price_usd    0
annual_price_usd     0
max_users            0
max_projects         0
storage_gb           0
is_active            0
created_at           0
dtype: int64

In [131]:
plan_df.to_csv("clean_plan.csv",index=False)

Team data

In [132]:
team_df.head()

,member_id,customer_id,email,full_name,role,is_active,invited_at,joined_at,last_login_at,created_at
0,1,1,joseph.nelson@rushplatform.com,Joseph Nelson,admin,1,2023-03-28 06:12:21,2023-04-06 21:02:07,2024-02-04 08:29:58,2026-05-30 00:06:49
1,2,1,sofia.wright@rushplatform.com,Sofia Wright,admin,1,2023-03-25 14:38:48,2023-04-02 05:26:38,2024-01-03 06:09:59,2026-05-30 00:06:49
2,3,1,yuki.martinez@rushplatform.com,Yuki Martinez,member,1,2023-03-09 00:47:39,2023-03-10 05:59:34,2023-05-08 15:58:07,2026-05-30 00:06:49
3,4,2,jennifer.adams@trekstack.com,Jennifer Adams,admin,1,2023-07-26 07:28:51,2023-08-02 06:06:53,2025-09-26 13:59:24,2026-05-30 00:06:49
4,5,2,richard.williams@trekstack.com,Richard Williams,billing,0,2023-07-09 22:14:41,NaT,NaT,2026-05-30 00:06:49

In [133]:
team_df.shape

(8500, 10)

In [134]:
team_df.isnull().sum()

member_id          0
customer_id        0
email              0
full_name          0
role               0
is_active          0
invited_at         0
joined_at        709
last_login_at    709
created_at         0
dtype: int64

In [135]:
team_df["joined_at"] = team_df["joined_at"].fillna("Not Joined")
team_df["last_login_at"] = team_df["last_login_at"].fillna("Never Logged In")

In [136]:
team_df.isnull().sum()

member_id        0
customer_id      0
email            0
full_name        0
role             0
is_active        0
invited_at       0
joined_at        0
last_login_at    0
created_at       0
dtype: int64

In [137]:
team_df.duplicated().sum()

np.int64(0)

In [138]:
team_df.to_csv("clean_team.csv",index=False)

Subscription data

In [139]:
subscriptions_df.head()

,subscription_id,customer_id,plan_id,status,billing_cycle,start_date,end_date,mrr_usd,discount_pct,trial_end_date,cancellation_reason,created_at
0,1,1,1,cancelled,annual,2023-01-31,2023-04-20,0.00,15.0,None,Missing features,2026-05-30 00:12:35
1,2,1,5,cancelled,annual,2023-04-20,2024-02-26,44.25,10.0,None,Switched competitor,2026-05-30 00:12:35
2,3,2,1,paused,monthly,2023-06-09,None,0.00,0.0,None,None,2026-05-30 00:12:35
3,4,3,1,active,annual,2023-10-28,None,0.00,20.0,None,None,2026-05-30 00:12:35
4,5,4,1,expired,annual,2024-04-09,2024-08-10,0.00,15.0,None,Budget cuts,2026-05-30 00:12:35

In [140]:
subscriptions_df.shape

(1840, 12)

In [141]:
subscriptions_df.isnull().sum()

subscription_id           0
customer_id               0
plan_id                   0
status                    0
billing_cycle             0
start_date                0
end_date                934
mrr_usd                   0
discount_pct              0
trial_end_date         1022
cancellation_reason    1060
created_at                0
dtype: int64

In [142]:
subscriptions_df["is_active_subscription"] = subscriptions_df["end_date"].isna()

subscriptions_df["is_on_trial"] = subscriptions_df["trial_end_date"].notna()

subscriptions_df["is_cancelled"] = subscriptions_df["cancellation_reason"].notna()

subscriptions_df["is_churned"] = subscriptions_df["end_date"].notna()

In [143]:
subscriptions_df.head()

,subscription_id,customer_id,plan_id,status,billing_cycle,start_date,end_date,mrr_usd,discount_pct,trial_end_date,cancellation_reason,created_at,is_active_subscription,is_on_trial,is_cancelled,is_churned
0,1,1,1,cancelled,annual,2023-01-31,2023-04-20,0.00,15.0,None,Missing features,2026-05-30 00:12:35,False,False,True,True
1,2,1,5,cancelled,annual,2023-04-20,2024-02-26,44.25,10.0,None,Switched competitor,2026-05-30 00:12:35,False,False,True,True
2,3,2,1,paused,monthly,2023-06-09,None,0.00,0.0,None,None,2026-05-30 00:12:35,True,False,False,False
3,4,3,1,active,annual,2023-10-28,None,0.00,20.0,None,None,2026-05-30 00:12:35,True,False,False,False
4,5,4,1,expired,annual,2024-04-09,2024-08-10,0.00,15.0,None,Budget cuts,2026-05-30 00:12:35,False,False,True,True

In [144]:
subscriptions_df.duplicated().sum()

np.int64(0)

In [145]:
subscriptions_df.to_csv("clean_subscription.csv",index=False)

billing data

In [146]:
billing_df.head()

,invoice_id,customer_id,subscription_id,invoice_date,due_date,amount_usd,tax_usd,total_usd,status,payment_method,currency,paid_at,created_at
0,1,963,1716,2025-08-06,2025-09-05,245.44,28.67,274.11,paid,credit_card,USD,2025-08-26 06:47:06,2026-05-30 00:12:44
1,2,1084,1707,2024-10-19,2024-11-18,99.76,7.04,106.80,paid,wire,USD,2024-10-23 02:44:11,2026-05-30 00:12:44
2,3,381,1747,2025-05-20,2025-06-19,117.82,3.43,121.25,paid,credit_card,USD,2025-05-25 00:34:12,2026-05-30 00:12:44
3,4,214,120,2024-02-20,2024-03-21,90.00,1.57,91.57,overdue,bank_transfer,GBP,NaT,2026-05-30 00:12:44
4,5,449,1150,2024-11-07,2024-12-07,67.54,1.58,69.12,void,wire,INR,NaT,2026-05-30 00:12:44

In [147]:
billing_df.shape

(15000, 13)

In [148]:
billing_df.isnull().sum()

invoice_id            0
customer_id           0
subscription_id       0
invoice_date          0
due_date              0
amount_usd            0
tax_usd               0
total_usd             0
status                0
payment_method        0
currency              0
paid_at            7564
created_at            0
dtype: int64

In [149]:
billing_df.duplicated().sum()

np.int64(0)

In [150]:
billing_df["is_paid"] = billing_df["paid_at"].notna()

In [151]:
billing_df.head(2)

,invoice_id,customer_id,subscription_id,invoice_date,due_date,amount_usd,tax_usd,total_usd,status,payment_method,currency,paid_at,created_at,is_paid
0,1,963,1716,2025-08-06,2025-09-05,245.44,28.67,274.11,paid,credit_card,USD,2025-08-26 06:47:06,2026-05-30 00:12:44,True
1,2,1084,1707,2024-10-19,2024-11-18,99.76,7.04,106.80,paid,wire,USD,2024-10-23 02:44:11,2026-05-30 00:12:44,True

In [152]:
billing_df.to_csv("clean_billing.csv",index=False)

feature data

In [153]:
feature_df.head()

,flag_id,plan_id,feature_key,feature_name,is_enabled,enabled_at,created_at
0,1,1,project_boards,Core project management boards,1,2023-01-25 18:02:58,2026-05-29 15:19:43
1,2,1,ai_task_suggest,AI-powered task suggestions,0,NaT,2026-05-29 15:19:43
2,3,1,gantt_charts,Gantt chart visualization,0,NaT,2026-05-29 15:19:43
3,4,1,time_tracking,Built-in time tracking,0,NaT,2026-05-29 15:19:43
4,5,1,resource_mgmt,Resource management & allocation,0,NaT,2026-05-29 15:19:43

In [154]:
feature_df.shape

(120, 7)

In [155]:
feature_df.isnull().sum()

flag_id          0
plan_id          0
feature_key      0
feature_name     0
is_enabled       0
enabled_at      26
created_at       0
dtype: int64

In [156]:
feature_df["is_enabled_flag"] = feature_df["enabled_at"].notna()

In [157]:
feature_df.duplicated().sum()

np.int64(0)

In [158]:
feature_df.to_csv("clean_feature.csv",index=False)

merging

In [159]:
df = activity.merge(subscriptions_df, on="customer_id", how="left")

df = df.merge(customers_df, on="customer_id", how="left")

df = df.merge(plan_df, on="plan_id", how="left")

In [160]:
df.head()

,customer_id,member_id,timestamp,event_type,page_url,session_duration_sec,browser,os,device_type,timezone_x,...,updated_at,plan_name,plan_tier,monthly_price_usd,annual_price_usd,max_users,max_projects,storage_gb,is_active_y,created_at
0,229,410.0,2024-01-16 10:13:48,form_submit,/projects/1779,2263.0,Chrome,iOS 17,mobile,UTC,...,2026-05-29 15:18:46,Enterprise,enterprise,99.0,990.0,500.0,0.0,100.0,1.0,2026-05-29 15:18:30
1,229,410.0,2024-01-16 10:13:48,form_submit,/projects/1779,2263.0,Chrome,iOS 17,mobile,UTC,...,2026-05-29 15:18:46,Professional Plus,professional,59.0,590.0,100.0,100.0,50.0,1.0,2026-05-29 15:18:30
2,14,2616.0,2024-06-12 13:27:31,search,/projects/3627,0.0,Safari,Windows 10,desktop,Asia/Kolkata,...,2026-05-29 15:18:46,Free,free,0.0,0.0,5.0,3.0,1.0,1.0,2026-05-29 15:18:30
3,14,2616.0,2024-06-12 13:27:31,search,/projects/3627,0.0,Safari,Windows 10,desktop,Asia/Kolkata,...,2026-05-29 15:18:46,Professional Plus,professional,59.0,590.0,100.0,100.0,50.0,1.0,2026-05-29 15:18:30
4,14,2616.0,2024-06-12 13:27:31,search,/projects/3627,0.0,Safari,Windows 10,desktop,Asia/Kolkata,...,2026-05-29 15:18:46,Enterprise,enterprise,99.0,990.0,500.0,0.0,100.0,1.0,2026-05-29 15:18:30

In [168]:
engagement_df= df.groupby("customer_id").agg({

    "session_duration_sec": "sum",
    "event_type": "count",
    "mrr_usd": "mean"

}).reset_index()

In [169]:
for col in ["total_session", "total_events", "avg_nps"]:
    col_min = engagement_df[col].min()
    col_max = engagement_df[col].max()
    engagement_df[f"{col}_norm"] = (
        (engagement_df[col] - col_min) /
        (col_max - col_min + 1e-9)      # +1e-9 prevents division by zero
    )

KeyError: 'total_session'

In [162]:
customer_data

  customer_id  session_duration_sec  event_type    mrr_usd
0          14                   0.0           3  44.416667
1         115                7059.0           3  24.610000
2         229                4526.0           2  55.525000
3         334                1460.0           2  32.500000
4         776                2915.0           1        NaN

In [163]:
df = df.drop_duplicates()

In [164]:
df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")

df["week"] = df["timestamp"].dt.isocalendar().week
df["month"] = df["timestamp"].dt.month
df["day"] = df["timestamp"].dt.date

In [165]:
print("Final Dataset Shape:", df.shape)
print("Nulls per column:\n", df.isnull().sum())

Final Dataset Shape: (11, 56)
Nulls per column:
 customer_id                0
member_id                  0
timestamp                  0
event_type                 0
page_url                   0
session_duration_sec       0
browser                    3
os                         3
device_type                3
timezone_x                 3
ip_address                 6
referrer                  11
feature                   11
subscription_id            1
plan_id                    1
status                     1
billing_cycle              1
start_date                 1
end_date                   5
mrr_usd                    1
discount_pct               1
trial_end_date             8
cancellation_reason        5
created_at_x               1
is_active_subscription     1
is_on_trial                1
is_cancelled               1
is_churned                 1
company_name               1
industry                   1
company_size               1
country_code               1
country_name               1
timezone_y                 1
contact_email              1
contact_name               1
signup_date                1
signup_source              1
is_active_x                1
churned_at                11
churn_reason               1
nps_score                  1
created_at_y               1
updated_at                 1
plan_name                  1
plan_tier                  1
monthly_price_usd          1
annual_price_usd           1
max_users                  1
max_projects               1
storage_gb                 1
is_active_y                1
created_at                 1
week                       0
month                      0
day                        0
dtype: int64

hypothesis

H0: High engagement users and low engagement users have same churn rate <br>
H1: High engagement users have lower churn rate

In [166]:
churned = df[df["is_churned"] == True]["engagement_score"]
active  = df[df["is_churned"] == False]["engagement_score"]

KeyError: 'engagement_score'

In [ ]:
churned = churned.dropna()
active = active.dropna()

In [ ]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(active, churned, equal_var=False, nan_policy="omit")

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: 0.5099153776923719
P-value: 0.6230084429977609

In [ ]:
alpha = 0.05

if p_value < alpha:
    print("Reject H0 → Significant relationship exists")
else:
    print("Fail to reject H0 → No significant relationship")

Fail to reject H0 → No significant relationship

Engagement does NOT significantly differ between churned and active users.

2 : H0: Paid users and Free users have the same engagement score<br>
H1: Paid users have higher engagement than Free users

In [ ]:
df["plan_tier"] = df["plan_tier"].str.lower().str.strip()

In [ ]:
paid_users = df[df["plan_tier"] != "free"]["engagement_score"]
free_users = df[df["plan_tier"] == "free"]["engagement_score"]

In [ ]:
paid_users = paid_users.dropna()
free_users = free_users.dropna()

In [ ]:
print(len(paid_users), len(free_users))
print(paid_users.nunique(), free_users.nunique())

10 1
5 1

In [ ]:
from scipy.stats import ttest_ind

t_stat, p_value = ttest_ind(paid_users, free_users, nan_policy="omit")

print("T-stat:", t_stat)
print("P-value:", p_value)

T-stat: 1.3800315149629172
P-value: 0.20088916521397374

In [ ]:
alpha = 0.05

if p_value < alpha and paid_users.mean() > free_users.mean():
    print("Reject H0 → Paid users have significantly higher engagement")
else:
    print("Fail to reject H0 → No significant difference")

Fail to reject H0 → No significant difference

The analysis suggests that engagement level alone is not a strong differentiator between free and paid users. This indicates that subscription upgrades may depend on other factors such as feature access, business needs, or pricing sensitivity rather than usage intensity.

segmentation

In [ ]:
num_cols = [
    "session_duration_sec",
    "mrr_usd",
    "nps_score"
]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [ ]:
df[num_cols] = df[num_cols].fillna(0)

In [ ]:
df["event_type"] = df["event_type"].fillna("unknown")

In [ ]:
customer_df = df.groupby("customer_id").agg({

    "session_duration_sec": "sum",
    "event_type": "count",
    "mrr_usd": "mean",
    "nps_score": "mean"

}).reset_index()

In [ ]:
customer_df = df.groupby("customer_id").agg({

    "session_duration_sec": "sum",
    "event_type": "count",   # OK (count works on object)
    "mrr_usd": "mean",
    "nps_score": "mean"

}).reset_index()

In [ ]:
df["event_flag"] = 1

In [ ]:
customer_df = df.groupby("customer_id").agg({

    "session_duration_sec": "sum",
    "event_flag": "sum",
    "mrr_usd": "mean",
    "nps_score": "mean"

}).reset_index()

In [ ]:
customer_df.columns = [
    "customer_id",
    "total_session_time",
    "total_events",
    "avg_revenue",
    "avg_nps"
]

In [ ]:
cols = ["total_session_time", "total_events", "avg_revenue", "avg_nps"]

for col in cols:
    customer_df[col] = pd.to_numeric(customer_df[col], errors="coerce")

customer_df[cols] = customer_df[cols].fillna(0)

In [ ]:
for col in cols:
    q1 = customer_df[col].quantile(0.01)
    q3 = customer_df[col].quantile(0.99)

    customer_df[col] = customer_df[col].clip(q1, q3)

In [ ]:
X = customer_df[cols]

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
customer_df["segment"] = kmeans.fit_predict(X_scaled)

In [ ]:
segment_summary = customer_df.groupby("segment")[cols].mean()
print(segment_summary)

         total_session_time  total_events  avg_revenue   avg_nps
segment
0                   6957.68      3.000000    24.610000  7.960000
1                   2915.00      1.040000     0.984400  0.200000
2                   2014.80      2.333333    43.999111  6.333333